[workspace]
resolver = "2"
members = ["crates/somnia-core", "crates/somnia-derive", "crates/somnia", "crates/somnia-cli"]

[workspace.package]
version = "0.5.1"
edition = "2021"
rust-version = "1.95"
license = "Apache-2.0"
authors = ["Vikram Bhaskaran <vikram.bhaskaran@outlook.com>"]
repository = "https://github.com/vbasky/somnia"
homepage = "https://github.com/vbasky/somnia"
keywords = ["surrealdb", "orm", "query-builder", "database", "surrealql"]
categories = ["database", "database-implementations"]
